#+TITLE: Mgła
#+AUTHOR: Aniceta Kubisiak

Listopadowe mgły utrzymują się bardzo długo, nieraz cały dzień. Taki mglisty
poniedziałek zmusza do refleksji nad sobą i nad światem. W gęstej mgle
człowiek czuje się potwornie samotny. Ale nie tylko mglista otoczka powoduje
poczucie samotności i odosobnienia. Jest to już we mnie przez całe
życie. A teraz jesień życia doskwiera mi okropnie. Starość jest jak śmierć ---
trzeba ją znosić samemu. Zegar biologiczny przyśpiesza, chwile mkną
bezpowrotnie. W międzyczasie nachodzą mnie czarne wspomnienia przeszłości,
a było ich co nie miara. Kiedy już nie mogłam sobie poradzić z natręctwem
powracających scen, zaczęłam prosić Boga, aby odsunął ode mnie koszmary. Wtedy
we śnie usłyszałam radę: /Nie patrz w przeszłość ani w przyszłość, rozejrzyj
się wokół siebie/. Od tego czasu jestem jakby spokojniejsza, mniej powrotów
w czarne dziury. Miałam kilka razy spotkanie z "nieznanym", a zawsze po tym
jakiś spokój i wyciszenie.

Urodziłam się w domu, którego nie ma. Pozostał pusty plac, zaniedbany
i zniszczony, a było tak pięknie. Dom wybudował dziadek w latach
trzydziestych, nie był co prawda wytworny, ale wychowało się w nim ośmioro
jego dzieci i następne pokolenie. Obszerna stodoła zajmowała dużą część
podwórza. Dziadek miał zawsze ambicję, aby być najlepszym rolnikiem we
wsi. Przed otrzymaniem ziemi z reformy rolnej w latach trzydziestych pracował
jako włodarz w majątku Ozdowskich i umiejętność kierowania i rozkazywania,
nieraz wprost uciążliwego, drzemała w nim. Brał czynny udział w pierwszej
wojnie światowej jako żołnierz niemiecki i po kielichu nie było końca jego
opowieściom o jego bohaterskich wyczynach. A mnie najbardziej utkwiła w
pamięci jego podróż powrotna z frontu. Szedł rzekomo pieszo od Marny przez
Wiedeń do Polski. Znał dość dobrze język niemiecki. Może te okoliczności
spowodowały, że nie został wywieziony do Generalnego Gubernatorstwa.

Jeśli już o dziadku mowa to trzeba stwierdzić, że to był bardzo prymitywny typ
--- warchoł i cham. Trzymał wszystkich twardą ręką, używał przemocy, bił tych
swoich synów, urządzał awantury. Nie pamiętam, by kiedyś splamił się
pracą. Wymagał tego od swoich synów, a on siedział i oceniał.

Babcia, kobieta spokojna, uległa i podległa, krzątała się ciągle przy
piecu. Żeby wyżywić tak liczną rodzinę, musiała cały dzień przygotowywać
posiłki. Dwaj jej synowie byli w Niemczech i bardzo się o nich
martwiła. Czekała na wiadomości od nich, popłakiwała nieraz, ale tylko to ja
widziałam. Nie była zbyt wylewna, spędzałam z nią dużo czasu, ale nie mogę jej
tak do końca rozszyfrować. Była niesamowicie pracowita, w ciągłym
ruchu. Ubierała się w długą spódnicę przepasaną fartuchem (zapaską). Miała
ciemne włosy zaczesane w koczek. Bardzo dbała o siebie i wokół
siebie. Utrzymanie w czystości tak licznej rodziny wymagało niesamowitego
wysiłku. Pranie urządzała w drewnianej, ogromnej balii z tarką i kotłem do
gotowania. Gotowała i krochmaliła. Dużo czasu pochłaniało prasowanie. Żelazko
było najpierw na węgle, a potem na duszę. Piekła najsmaczniejszy na świecie
chleb. Piec znajdował się w sieni (długi korytarz). Najpierw zarabiała ciasto,
a kiedy ono rosło paliła w piecu drewnem. Do nagrzanego pieca na specjalnej
szufli wsuwała uformowane bochny chleba. Potrzeba było prawdziwego
mistrzostwa, aby pieczywo było jadalne. Umiejętność ta przechodziła
z pokolenia na pokolenie.


* Dzieciństwo

Przyszłam na świat w niefortunnej rodzinie i w niefortunnym okresie. Rodzice
po 4 klasach szkoły podstawowej i bez zawodu, bez pracy i zabezpieczenia
materialnego, pozostawali na utrzymaniu dziadków. Ojciec odbył służbę wojskową
w Korpusie Ochrony Pogranicza w Kowlu (obecnie Białoruś). Ożenił się, gdy miał
27 lat i wtedy musiał zadbać o rodzinę. Pracował u rolników podczas prac
sezonowych w polu, odbierał w starostwie darmowe bochenki dla
bezrobotnych. Jego narzędziem pracy, można tak powiedzieć, był rower. Zimową
porą po prostu kradł --- wstyd o tym wspominać. Nie wiem, jak to robił, ale
potrafił młócić rowerem zboże ze stogów i ziarno sprzedawać, podkradał również
ziemniaki z kopców. Takie to były czasy i obyczaje.

Urodziłam się w domu, ale po dwóch dniach znalazłam się w szpitalu, ponieważ
podczas kąpieli mama złamała mi rękę. Na pewno byłam oczekiwana i kochana, ale
tego nie pamiętam. Imię dla mnie wybrał ojciec z jakiegoś romansu francuskiego
i muszę przyznać, że wywoływało w moim życiu sporo zamieszania. Pewnie takie
masz imię, na jakie zasługujesz. Wynika z tego, że ojciec czytał, sporo
czytał.

Imię było zawsze dla mnie wyróżnikiem; na poczcie, w banku, w szkole, na
studiach .Zaczynało się od tego, że niespotykane, że oryginalne, że
dostojne. Nie spotkałam nikogo o tym samym imieniu, chociaż w niektórych
kalendarzach 17 kwietnia figuruje. Przełamywało lody nawet na studiach,
rozpoczynało dyskusję. W średniowieczu imię Anicet nosił jeden z papieży. Co
prawda nieraz je zniekształcano, ale ogólnie nie ciążyło mi.

Często zastanawiam się nad sobą, dlaczego jestem jaka jestem. Nie utrzymuję
specjalnych kontaktów z rodziną. Nie mam z nimi wspólnych tematów, wyrastam
jak gdyby ponad. Jedyna   z obu rodzin ukończyłam studia. Może to geny mojej
babci ze strony ojca, która była rzekomo córką dziedzica. Rodzina Rutkowskich
(samo nazwisko znane i bardzo szlachetne, wielu znanych lekarzy, muzyków)
ogólnie sprawiała wrażenie zdolnych, o różnych zainteresowaniach.  Szczególnie
Tadeusz, ale o nim później. Ja natomiast wychowywałam się przy rodzinie
Jadłowskich, tumanach, pijakach i nieukach. Pisać i czytać oni co prawda
trochę umieli no ale jak nie umieć, gdy do szkoły chodziło się siedem lat
kończąc 4 klasy (do czwartej klasy uczęszczało się trzy lata). Przyznać
należy, że umieli śpiewać po kielichu, głośno śpiewać, przede wszystkim
piosenki wojskowe np. wojenko, wojenko itp.

Zawsze wszystkim tłumaczę, że wychowanie dziecka do lat trzech no może siedmiu
stanowi bazę jego przyszłego życia. Mówię to jednak na podstawie moich
najdroższych wnuków. Moje dzieciństwo temu zupełnie zaprzecza. Wojna to jest
straszny okres dla dziecka. Słowami się tego nie da opisać. Strach, ciągły
strach. Stało się to 1 września 1939r., miałam szesnaście miesięcy. Ten dzień
znam tylko z relacji. Społeczeństwo nie było zupełnie przygotowane do
wojny. 31 sierpnia ojciec stawił się w 63 pułku piechoty we Wrześni. Więc coś
się działo. W napięciu i ciszy wszyscy czekali. Radia i telewizji nie było,
gazety przynoszą opóźnione wiadomości. Dopiero 1 września rano rozległy się
syreny i eksplozje bomb spadające na dworzec kolejowy we Wrześni.

Nastąpiła straszna panika. Dziadek Jan postanowił się z rodziną ewakuować. Na
największy wóz zaprzężony w dwójkę koni załadowano pościel, zabitego prosiaka
wszystkich członków rodziny (dziewięć osób ze mną), za wozem krowa
i ruszyliśmy w kierunku Gniezna. Straszna desperacja, nawet nie zamknięto
domu. Wszyscy uciekali w różnych kierunkach. Zero informacji.

W tym czasie mój ojciec maszerował z Wrześni do Gutowa Wielkiego wraz ze swoim
pułkiem na pociąg, ponieważ z dworca wrzesińskiego nie można było
odjechać. Wstąpił po drodze do opuszczonego przez nas domu, aby zabrać
sznurowadła (żołnierze dostali buty bez sznurowadeł --- co za ironia
losu). Zabrał co trzeba i pojechał w kierunku Kutna. Walczył pod dowództwem
Kutrzeby w Armii Poznań, wiadomo z historii o bałaganie w prowadzeniu wojny, o
braku koordynacji. On to wszystko przeżywał. Wiem, że walczył nad Bzurą,
a potem przerzucono ich pod Modlin. Niechętnie opowiadał o tym okresie
życia. Mówił tylko, że tam zobaczył piekło. Od tego czasu przestał
wierzyć. Pod Modlinem został ranny w nogę. Przez dwa lata przebywał w obozie
jenieckim w Prusach Wschodnich, a następnie wywieziono go do pracy do
Niemiec. Zatrudniony był u bauera w okolicach Disseldorfu. Gospodarstwo
prowadziła kobieta, ponieważ jej mąż walczył na wschodzie. Było tam kilku
jeszcze innych Polaków i na ten okres życia nie narzekał.

Trzeba wrócić do naszej niefortunnej ucieczki. Dojechaliśmy pod Grzybowo, a tu
samoloty niemieckie koszącym lotem czyściły drogi. Uniknęliśmy najgorszego
i trzeba było wracać z powrotem. Krowa się opierała, a w zagrodzie czekał cały
inwentarz. Trzeba było wrócić do codziennych obowiązków. Dochodziły wieści, że
Niemcy opanowali Wrześnię i rozstrzelali kilkunastu wrześnian
w Dębinie. Zawsze tak postępowali, żeby pokazać, kto tu rządzi. Do Gutowa też
zawitali. Mieli przygotowaną listę mieszkańców, perfekcyjnie opracowaną, przy
każdym nazwisku jego przyszłość. Jedni do gazu, drudzy do Generalnego
Gubernatorstwa, reszta zostaje jako parobcy u Niemców. Wszystkim odebrano
gospodarstwa i przydzielono je Niemcom. Nie wiem skąd ci Niemcy tak szybko się
wzięli. Były to przeważnie kobiety z dziećmi. My należeliśmy do tej grupy
trzeciej.

Zabrano dziadkowi gospodarstwo, połączono je z sąsiednim, a on ze swoimi
synami pracował u Niemki Szulc na przeciwko szkoły. Z domu, w którym
dotychczas mieszkaliśmy, urządzono magazyn zbożowy, a nas przeprowadzono do
domu Kulczaków. Mieszkały tu dwie starsze kobiety z kotami. Mogliśmy zabrać
meble i rzeczy osobiste, natomiast zwierzęta gospodarcze i maszyny przejął
Niemiec. Po 1941r.,kiedy Niemcy opanowali południe Związku Radzieckiego,
przybyli nowi Niemcy znad Morza Czarnego i ci dotychczasowi musieli się z nimi
podzielić gospodarstwami. Dotychczas zastanawiam się, jacy to Niemcy i skąd
oni się wzięli nad Morzem Czarnym.

A teraz życie codzienne. Była to prawdziwa okupacja. Wioską zarządzał Niemiec,
taki w randze sołtysa. Polakom nie wolno było opuszczać wioski bez specjalnej
przepustki. Nie chodziliśmy do kościoła, nie było szkoły, a nauczycieli
wywieziono do obozów. Zabroniono rozmawiać o polityce, wiadomości przekazywano
sobie szeptem. Zresztą żadnych wiadomości nie było, nie wiadomo gdzie był
front, kto z kim walczy --- żadnych komunikatów, prasy. Każdy musiał
zaopatrzyć się w zaciemniacze okien (usztywnione czarne płótna), przed
zmrokiem należało zaciemnić okna, aby najmniejszy promyk światła nie wydostał
się na zewnątrz. Zresztą nie bardzo co się miało wydostawać, ponieważ nie było
czym oświetlać mieszkań. Przed wojną używano lamp naftowych, teraz z wiadomych
względów nafty nie było. W tym celu używano karbidu, była to biała papka,
w nią wkładano knot i kopciło a kopciło.  Chodziło się wcześnie spać
i nadsłuchiwało się przelatujących niemieckich bombowców. Ziemia drżała, kiedy
leciały na wschód. Mieszkaliśmy ok. 100 m .od toru kolejowego i wyładowane
pociągi towarowe też mknęły w tym samym kierunku.

We wsi znajdował się jeden sklepik dla Polaków i tam wszystko na
kartki. Sławetna margaryna, której smak do dzisiaj pamiętam, była jedynym
tłuszczem. Jednak najdziwniejsze były cukierki, bryłki przetopionego cukru ze
sznurkiem w środku. Nie można było nic hodować. Nie było czym karmić, a poza
tym każdy żywy inwentarz należało zgłaszać urzędującemu Niemcowi. Jedzenie
było kiepskie, jednostajne. Nieraz dziadek, który wraz ze swoimi synami
pracował u Szulcowej, przynosił trochę jajek, mleka, a po świniobiciu nawet
mięsa. Niemka wysyłała swojemu mężowi paczki na front wschodni i dlatego
hodowała dużo świń.

Niedziele i święta nie bardzo różniły się od dni powszednich.Niemcy bardzo
gwarnie i wesoło obchodzili Boże Narodzenie. Oświetlone domy, choinki i "O
Tanenbaum" rozlegało się po całej wsi. Szczególnie głośni i aroganccy byli
młodzi Niemcy, ubrani w mundury wojskowe najbardziej pilnowali swoich
zdobyczy. A u nas w tym czasie cicho i ciemno. Mieliśmy spakowane
najpotrzebniejsze rzeczy tzn. ubrania i buty w specjalnych pakunkach, każdy
swoje i czekaliśmy każdej nocy na łomotanie do drzwi. Podjeżdżali ciężarówką
i krzycząc, dawali 15 min. na wyjście. Przejmujący strach towarzyszył mi od
pierwszych chwil świadomości. Strach, ciemno i głodno.

W Gutowie Małym i Białężycach zorganizowano ogrodnictwo dla potrzeb wojska,
którym kierował her Walter. W tych placówkach pracowała moja mama, od świtu do
nocy. Do Białężyc wozili ich wozami konnymi. Nieraz udało jej się przynieść
dwie lub trzy cebule i wtedy kolacja była "pyszna".

Her Walter mieszkał w pałacu z rodziną, miał córkę w moim wieku .Którejś
niedzieli szłam z mamą na spacer przy ogrodzeniu parku i ta pięknie ubrana
dziewczynka podeszła do płotu i uśmiechnęła się do mnie. Ten uśmiech
prześladował mnie, marzyłam, że kiedyś się z nią spotkam, zaprosi mnie do
pałacu i będę się z nią bawić. Miałam takie piękne marzenia, czekałam na nią
przy furtce, wyglądałam jej karety i zamykałam oczy, śniąc na
jawie. Przekonałam się wtedy, że najpiękniejsze w życiu są marzenia, nie muszą
się spełnić, ale byle były.

Mama wychodząc do pracy powtarzała
codziennie --- /Uważaj na listonosza, na pewno przyniesie list od taty/. Siedziałam
pod furtką, czekałam. Listy przychodziły rzadko. Wychowywała mnie w kulcie dla
ojca, nie wiem tylko, czy to było warto. Obiecywała, jak to będzie dobrze, gdy
ojciec wróci, stale mi o nim przypominała. Wierzyłam w to, ale zderzenie
z rzeczywistością było tym bardziej bolesne. Wieczorami opowiadała mi, że
kiedyś się zmieni że skończy się wojna a ja będę chodziła do szkoły i gdy będę
się dobrze uczyła, to na pewno dostanę pracę w biurze i będę jadła cienkie
skibki chleba z masłem. Jakie to było dla mnie piękne. Nie wiedziałam, co to
szkoła, co to biuro, ale marzyłam, strasznie marzyłam. Nigdy nie słyszałam
żadnej bajki na dobranoc. Nie miałam żadnych zabawek, żadnych. Prosiłam, żeby
mi mama opowiadała, jak wygląda szkoła, co się tam robi. Dowiedziałam się, że
są jakieś zeszyty, książki. To wszystko jednak była sfera wyobraźni. W domu
nie było żadnego papieru, zeszytu czy książki, gazety ani najmniejszej kartki,
ołówka czy kredki. Jedynym papierem były karty do gry.

Dorośli wieczorem wyżywali się w Tysiąca, a w dzień było to moje
królestwo. Babcia zapracowana nie zwracała na mnie uwagi, wtedy zabierałam
karty, siadałam gdzieś w kąciku, najczęściej na strychu i wymyślałam różne
historie. Osoby z kart ożywały, prowadziłam z nimi dialog, żaliłam się ze
wszystkiego co mnie boli. Budowałam domki z kart, pałace, zagrody. Zazwyczaj
w niedziele domownicy siadali na ławce pod oknem na dworze, czekałam na tę
chwilę cały tydzień, miałam przygotowane patyki i prosiłam o pisanie mi liter
i cyfr na ziemi. Utrwalałam to sobie przez cały tydzień czekałam do następnej
niedzieli. W ten sposób nauczyłam się pisać, liczyć i czytać. Inna forma mojej
zabawy to lepienie różnych figur i budowli z gliny. Na podwórku była kupka
gliny do wylepiania pieców. Polewałam ją wodą i brudziłam się po łokcie. Była
to wspaniałe zajęcie.  Zazwyczaj kończyło się katastrofą. Cztery lata starszy
ode mnie Zygmunt, brat mamy, umysłowo niedorozwinięty, niszczył mi moje
dzieło. Zazwyczaj deptał i tak szalenie się z tego cieszył, że do dziś
wspominam jego dziki śmiech i to, że czekał, kiedy skończę, aby dać upust swej
głupocie. Więc nie tylko Niemcy, ale i najbliższe grono uprzykrzało mi
życie. Przy domu Kulczaków była piwnica. Kopano dół w ziemi, gdzieś na
głębokość 1 m. dach wykonywano z żerdzi, na to kładziono słomę i ziemię
i miało to służyć do przechowywania ziemniaków i warzyw. W wejściu do piwnicy
stał stary, zepsuty rower. Nie miał łańcucha ani opon, ale można było na nim
usiąść i pedałować. Wkradałam się tam często i zwiedzałam wymarzone
krainy. Takie to były moje zabawy w tych odległych latach. Troszkę musi
wystarczyć za wiele.

Miałam jednak też pewne obowiązki. Prawie codziennie musiałam wieczorem
przekradać się opłotkami do Bartkowiakowej po "bombkę" dla dziadka. Było to
strasznie niebezpieczne, godzina policyjna, ja biegnę po alkohol dla mojego
"ukochanego" dziadziusia. Prawie codziennie chodziłam z babcią do
Solarka. Babcia była bardzo wrażliwą osobą, skora do pomocy,
litościwa. Zanosiłyśmy mu jedzenie. Był samotny, stary, pewnie spokrewniony
z babcią. Miał bardzo długą, siwą brodę, kostur na którym opierał
ręce. Siedział na ławce w swojej kuchni i milcząco czekał. Babcia prała mu
ubrania, sprzątała, pocieszała.

Ale najbardziej podziwiam moją babcię, za moim zdaniem heroiczny czyn, za
pomoc Żydom. Jak już wspomniałam, mieszkaliśmy niedaleko torów
kolejowych. Była to bardzo ważna linia kolejowa z zachodu na wschód. Według
pociągów nastawiało się zegarki, godna pozazdroszczenia punktualność. W czasie
wojny tą trasą jeździły pociągi z dostawami na front. Ruch był ogromny. Tory
trzeba było naprawiać. Do tych prac angażowano Żydów. Przetrzymywano ich
w obozie pracy w Otocznej. Obrazek, który utrwalił mi się w pamięci. Zima,
mróz trzaskający niczego. Babcia mówi do mnie, że pójdziemy na
spacer. Zdziwiona tą propozycją ubieram moje dybki, coś tam jeszcze
i wychodzimy. Babcia chowa pod swoim nieodłącznym fartuchem bochen
własnoręcznie upieczonego chleba. Myślałam, że idziemy do Solarka. Mijamy jego
zabudowania. Idziemy dalej. Zakręt. Babcia spogląda w dal, podążam za jej
wzrokiem i widzę dziwną gromadę ludzi pracujących na torach. Dlaczego dziwną?
Wszyscy jednakowo ubrani w pasiaki, na głowach pasiaste czapki. Kilkanaście,
może więcej, osób. Zbliżmy się wolno do nich. Cisza, słychać tylko odgłos
stukających narzędzi. Wśród nich Niemcy nadzorujący pracę. Babcia nerwowo
ściska mnie za rękę. Dochodzimy do pracujących, babcia wyciąga chleb i podaje
pierwszemu z brzegu. Dziękczynny wzrok, bez słowa. Niemcy widzą, ale nie
widzą. Dokonał się wielki akt łaski w niemej ciszy. Na bosych nogach klompy
(całe buty wystrugane z drewna). Taki mróz. Jutro tu jeszcze wrócimy. Rytuał
ten sam. Potem już ich nie będzie. Nikt z domowników nie wiedział o naszych
wyprawach. Dopiero dzisiaj zdaję sobie sprawę, jakie nam groziło
niebezpieczeństwo. Babcia wtedy o tym wiedziała i tak sobie myślę, co ją
popchnęło do tak ryzykownego kroku. Mogli przecież nas na miejscu zastrzelić
albo zaaresztować i wywieźć gdziekolwiek. Czym się człowiek kieruje? Jest
jakaś wewnętrzna siła, niezależna i podświadoma, kierująca postępowaniem
człowieka. Ktoś powiedział, że gdy dajesz komuś, zwraca ci się podwójnie. Ona
wtedy o tym nie myślała. Jestem z niej bardzo dumna.

Przez okres okupacji byłam we Wrześni dwa razy. Jeden raz u fotografa, aby
wysłać ojcu do Niemiec zdjęcie, a drugi raz u dentysty. Bardzo bolał mnie
ząb. Było to latem, cała buzia mi opuchła. Na cały powiat był dla Polaków
jeden dentysta. Pamiętam przejmujący ból i pieszą wędrówkę do
Wrześni. W poczekalni przestało mnie boleć i uprosiłam mamę, abyśmy wracały do
domu Po powrocie znowu ból ale do wizyty u dentysty nie doszło. W tym czasie
i jeszcze długo po wojnie nie używało się szczoteczek do zębów. W ogóle nie
myło się zębów, ja dopiero nauczyłam się tej czynności w liceum. Z higieną
osobistą też zawsze był problem, a może nie było problemu, ponieważ rzadko
ludzie się myli. W porównaniu z obecnymi czasy to było średniowiecze. Brud
powoduje choroby, jednak z tego czasu nie przypominam sobie żadnej
epidemii. Ubrania przerabiano ze starych, szyto mi jakieś suknie. Najbardziej
jednak pamiętam moje sławetne dybki, których nazwy nawet komputer nie
zna. W sąsiedztwie mieszkał szewc Rewers i on mi obijał drewniane spody
wierzchem z innych butów. Były tanie i trwałe. Latem miałam sandałki też
z drewnianymi spodami, tylko na wierzchu były paski. W takich butach chodziłam
jeszcze do szkoły w latach pięćdziesiątych. Wszystko to z powodu niedostatku
i biedy. Babcia dziergała skarpetki dla wszystkich domowników, moja mama też
się tego nauczyła. Często byłam zaangażowana w prucie starych skarpet
i zawijanie wełny. Jednak umiejętność robótek pochłonęła mnie całkowicie
w latach osiemdziesiątych.

Wracając do czasów okupacji pamiętam jeszcze jeden przykry incydent. Siostra
mamy Czesława została powiadomiona na jesieni czterdziestego czwartego roku o
przymusowym wyjeździe do pracy w Niemczech. Miała tam pracować
w fabryce. Przyjechała ciężarówka, zatrzymała się na skrzyżowaniu dróg i kilka
osób z Gutowa zabierała. W domu była rozpacz Jednak odwołać wyjazdu nie było
można. Odprowadziłam ją razem z Zygmuntem do samochodu. Po pożegnaniu
wracaliśmy do domu. Zaczepił nas młody Niemiec, zaczął nas przezywać po
niemiecku, Zygmunt nie namyślając się długo rzucił w niego
kamieniem. Wywiązała się straszna awantura, dziadek musiał przepraszać Niemca,
tzn. ojca tego młodego, jakoś to potrafił zażegnać. Od tego czasu nie
wychodziliśmy na drogę. Nie jestem w stanie oddać całej tragedii tego okresu,
koszmarnego snu, z którego chcieliśmy się jak najprędzej przebudzić.

Dzisiaj jest 19 stycznia 2007r. Zimy tego roku wcale nie ma. Jeszcze nie padał
śnieg, nie było mrozu. W ogródku kwitną krokusy i przebiśniegi. Dzisiejszej
nocy wiał silny huragan Cyryl. Narobił strasznych szkód w całej Europie,
w Polsce zginęło 6 osób. W ogródku złamał śliwę, naderwał morwę i trochę
zniszczył orzech. Takiego huraganu to jeszcze nie pamiętam, przerażające
wycie, deszcz, chmury deszczu i taki straszny hałas. Przyroda ostatnio bardzo
się zmienia. Lato było bardzo upalne i suche, teraz nie ma zimy i co będzie
dalej?

Natomiast zima 1945 roku należała do typowo polskich. Spadło dużo śniegu, mróz
silny, niebo wyiskrzone gwiazdami. W taki wieczór zebrali się u dziadka
sąsiedzi --- Polacy i nadsłuchiwali ciężkich wystrzałów artyleryjskich,
przelotu bombowców. Ziemia drżała. Radość była niesamowita, podniecenie
również. Nie było wiadomo, gdzie jest front, ale było wiadomo, że gdzieś
blisko. Domyślano się, że najdalej może być w Koninie. Długo w noc trwały
Polaków rozmowy. Niemcy w panice pakowali się i uciekali. Wczesnym rankiem 20
stycznia, brat mamy Wiktor, 17-letni chłopak, został zmuszony przez Szulcową
do odwiezienia jej do Niemiec. Kareta zaprzężona w dwa piękne konie mknęła na
zachód. Niemka i jej dwoje dzieci, na koźle Wiktor, a za nimi front. Na drugi
dzień Wiktor wrócił do domu. Pod Poznaniem powiedział Niemce, że musi iść do
lasu się załatwić i po prostu uciekł do domu. Wracał polami, drogi były zajęte
przez wojsko. Ciekawi mnie nieraz, jakie były dalsze losy tej kobiety, powozić
nie umiała. A u nas w domu po nieprzespanej nocy nie było wiadomo co
dalej. Niemców nie było, Rosjanie jeszcze nie weszli. Pustka i wyczekiwanie.

Pod wieczór pojawili się wyzwoleńcy. Ludzie grupkami stali na drodze
i czekali. Wpadli do wsi na motocyklach z przyczepami
i samochodami. Zatrzymali się przy naszym domu, ponieważ tu stało najwięcej
osób. Uściskom i pocałunkom nie było końca. "Hitler kaput" --- słyszało się
wokół. Tych kilkunastu oficerów rosyjskich zaprosił dziadek do domu. Babcia
przygotowywała kolację, mama i ciotki pomagały. Rosjanie wyciągali swoje
zapasy, kładli wszystko na stół. Rozpoczęła się uczta, której nie zapomnę do
końca życia. Przyszli inni Polacy --- sąsiedzi. Gwar rozmów, śmiechy,
opowiadania i pytania, czy to już naprawdę koniec. Było to dla mnie
niesamowite przeżycie. Byłam chyba tam jedynym dzieckiem i każdy żołnierz
chciał mnie dotknąć i uściskać, mieli również rodziny i chyba bardzo za nimi
tęsknili. Wtedy po raz pierwszy zobaczyłam cukier, posmakowałam szynki
i czekolady, piłam prawdziwą herbatę. Jaki cudowny wieczór! Wczesnym rankiem
zbierali się do odjazdu. Myli się przy studni w lodowatej wodzie. Jeden
z żołnierzy w randze kapitana, bardzo polubił moją babcię, która przypominała
mu własną matkę i przyrzekł, że w drodze powrotnej na pewno nas odwiedzi. Nie
dotrzymał słowa, a może nie było drogi powrotnej.

Niemcy z Wrześni i z okolicznych wsi uciekli bardzo szybko. Kilku jednak
ostrzeliwało się z wieży ciśnień we Wrześni, a Rosjanie nie chcieli tej
budowli wysadzić. Niemcy w końcu musieli się poddać. Front przesuwał się na
zachód, a za nim szły grupki lub pojedynczy żołnierze i ci najbardziej dawali
nam się we znaki. Kradli, gwałcili a nawet zabijali. Powstała Straż
Obywatelska złożona z Polaków i pilnowała porządku. Miała pełne ręce
roboty. Moja mama i jej dwie siostry przez dwa tygodnie przebywały na strychu
nad chlewem i tam babcia, niby karmiąc świnie, zanosiła im pożywienie. Minął
jeden horror, przyszedł następny. Pewnego dnia wtargnął do nas rosyjski
żołnierz, który miał pełen worek zegarków różnego kalibru. Wysypał je na
podłogę i zaczął przeglądać. Nakręcał je i cieszył się jak
dziecko. Przestraszył się, kiedy nakręcił budzik i zaczął mu dzwonić -
wyrzucił go, bo myślał, że ktoś do niego strzela. Inny znowu, po splądrowaniu
chlewa, zażyczył sobie upieczenia małego prosiaczka. Ani babcia ani dziadek
nie chcieli mu go zabić. Sam dokonał tej czynności, a resztę musiała babcia mu
upiec. Pamiętam moje zdenerwowanie, zatykanie uszu i niepowstrzymany płacz. Na
babcię mówiłam "mama", żeby żołnierze nie domyślili się o kryjówce, myliło mi
się ciągle.

Po cudownym pierwszym wieczorze, przeprowadziliśmy się do naszego domu. To co
działo się w ciągu tego dnia trudno oddać słowami. Szaber! Wielki Szaber!
Polacy, którzy pozostali we wsi kradli, wszystko kradli. Rodzina Jadłowskich
oszabrowała gospodarstwo po Szulcowej, a potem inne. Budynek gospodarczy był
niewielki. Nasprowadzali tyle zwierząt gospodarskich, maszyn rolniczych, mebli
i tyle różnych rzeczy, ze nie jestem w stanie tego wszystkiego wymienić. Po
raz pierwszy jadłam kompot z czereśni --- pycha. Przyniesiono mi też buty ---
tenisówki, kilka numerów za duże, zmniejszyłam je za pomocą słomy. Co za
radość! Otrzymałam pierwszą w życiu zabawkę. Był to drewniany piesek na
kółkach, beżowy z czerwonym języczkiem. Dostałam jakieś ubrania po dzieciach
niemieckich. Dom pełen, obora pełna, stodoła pełna. Musiał dziadek swojego
dobytku dobrze pilnować, ponieważ grasowały szajki złodziejskie i bezpardonowo
zabierały wszystko. Kiedy wrócili rolnicy wywiezieni do Generalnego
Gubernatorstwa, zastawali zazwyczaj pustki w swoich gospodarstwach.

Nie dane jednak było się cieszyć długo zdobyczami. W kwietniu żołnierze
rosyjscy wracając z frontu zabierali z gospodarstw wszystko, co się
ruszało. Stałam przy furtce i widzę wlokące się konie, krowy, świnie, owce
w różnym wieku i maści. Cała droga zajęta. Rosjanie chodzą od jednego
gospodarstwa do drugiego i wypędzają wszystkie zwierzęta na drogę. Gnają je na
pociąg towarowy, który stał w Gutowie Wielkim. Do dziadka przyjechał jego
siostrzeniec, który pracował w Służbie Ochrony Kolei. Ubrany był w granatowy
mundur i miał broń. Może ta wizyta nie była przypadkowa. Dziadek stał z nim
przy bramie i nerwowo wyczekiwał na żołnierzy. Jeden z Rosjan machnął ręką
i poszli dalej. A ja dalej patrzę na niesforne stado, które nie bardzo ma
ochotę na przejażdżkę pociągiem. Jedna ze świń, które wiadomo, że nie są
dobrymi piechurami, przewróciła się w rowie i tak ją zastrzelono. Co kawałek
po drodze coś padało, a potem trzeba było zrobić wielkie sprzątanie. Dziadek
był w tym dniu najszczęśliwszym człowiekiem. Wracając do zwierząt, zastanawiam
się, dokąd one mogły dojechać. Pociągi wolno jeździły, ponieważ były
zniszczone tory, brak jedzenia dla nich i po co to wszystko.


* Tadeusz, czyli tajemnica Syberii

Rodzina Rutkowskich mieszkała w Gutowie Małym pod Kleparzem, drugi dom od
końca po lewej stronie. Obejście pomysłowo zagospodarowano. Po prawej stronie
stał dom mieszkalny razem z gospodarczym, nad nimi strych. Wejście na strych
znajdowało się na zewnątrz. Na wprost wybudowano dużą stodołę, za nią kierat
(urządzenie do uruchamiania młockarni i sieczkarni). Po lewej stronie
usytuowano szopy i letnią kuchnię. Od drogi do podwórka prowadziła dróżka,
a po obu jej stronach ogródek kwiatowy i warzywny oraz sad. Przy budynkach
znajdowało się pole ciągnące się pod samo Ostrowo Szlacheckie. Mieszkanie
składało się z dwóch gustownie urządzonych pokoi i dużej kuchni. Kuchnia
stanowiła kluczowe miejsce w dawnych rodzinach, tutaj się przygotowywało
i spożywało posiłki. Stał długi stół, przy nim ławki. Znajdował się też
kredens oraz duży piec kuchenny. Dwa okna, zawsze posiadające ładne firanki,
dawały dużo światła. Przed wejściem do kuchni stała przybudówka chroniąca
przed zimnem, a jednocześnie jako schowek na drobne narzędzia.

Babcia moja, Franciszka z Bagrowskich Rutkowska, wymaga szczególnego
przedstawienia, ponieważ wmawiano mi ciągle, że mam po niej charakter. Ona to
dbała, aby jej rodzina byłą syta i czysta, udawało jej się to
znakomicie. Najstarsza córka Katarzyna wyszła za mąż jeszcze przed wojną, więc
sama musiała utrzymywać dom i ogród. Miała siedmioro synów: Leon, Czesław,
Józef, Stefan, Marian, Tadeusz i Florian. Wiadomo, że chłopcy nie bardzo
kwapią się do prac domowych.

Nie odwiedzałam babci, kiedy ojciec był w niewoli, natomiast pamiętam, że ona
często przychodziła do nas. Moja mama nie była rada z jej wizyt. Zresztą, moja
mama była bardzo dziwnym człowiekiem. Ciągle musiała się na kogoś gniewać,
wiecznie obrażona, nadąsana. Nie wiem, jakie miała pretensje do babci
Franciszki, ale nie wyrażała się o niej najlepiej. Babcia nie zniechęcała się
fochami synowej, odwiedzała nas, brała mnie na kolana, przytulała i przynosiła
zawsze coś dobrego. Kiedy przed wojną kobieta rodziła szóstego syna, była
szczególnie wyróżniana przez państwo. Synowie to przyszli żołnierze, a takich
potrzebował Marszałek Piłsudski. Chrzestnym Tadeusza był sam Marszałek, taka
była tradycja. Przysyłał swego adiutanta z prezentem i taki chłopiec korzystał
ze specjalnych przywilejów. Dziwny był wtedy system oświaty z podziałem na
dzieci wiejskie i miejskie. We wsiach były szkoły 4-klasowe i uczęszczało się
do nich siedem lat powtarzając po prostu klasy. Natomiast w miastach istniały
szkoły 7-klasowe i po nich można było kontynuować naukę w 4-letnich
gimnazjach, a potem ewentualnie studia. Dla dzieci wiejskich taka droga
edukacji była zamknięta. Tadeusz miał umożliwioną naukę w szkole miejskiej,
z czego niewątpliwie skorzystał. We Wrześni była jedna szkoła podstawowa
(obecna nr. 1) i do niej Tadeusz uczęszczał, a po ukończeniu kontynuował naukę
we wrzesińskim gimnazjum (obecne liceum). Uczył się bardzo dobrze, ale wybuch
wojny pokrzyżował dalsze plany. Co robił i gdzie przebywał podczas wojny, nie
wiem. Na pewno nie było go w Gutowie.

Nie sposób pominąć pewnego wydarzenia, które miało miejsce pod koniec 1944
roku. Pewna kobieta ubrana w niebieską suknię spacerowała z niemieckim
żołnierzem do Borku (niewielki lasek za torami kolejowymi). Miało to miejsce
w październikową niedzielę i tą parę ktoś widział. Kobietą miała być moja
mama. W niebieskich sukniach chodziło wiele kobiet, bo tylko taki materiał
mogły Polki kupować (coś podobnego jak w Chinach), ale to była
okupacja. Babcia Rutkowska napisała list do mojego ojca, ze szczegółami
opisała zajście dodając co o tym sądzi. Według niej to była na pewno moja
mama. Nie darzyła jej nigdy specjalną sympatią i teraz nadarzyła się okazja,
by dać upust swemu uczuciu. Moja mama była zaskoczona, kiedy otrzymała list od
ojca, który kategorycznie z nią zrywał, oczywiście uzasadniając swą
decyzję. Starała się wytłumaczyć małżonkowi absurd oskarżeń, ale był
niewzruszony i więcej nie pisał. Tragedia w rodzinie. A ja i tak codziennie
wychodziłam do furtki, czekałam na listonosza, ponieważ nic nie wiedziałam. To
była taka rodzina, która szeptała coś stale po kątach, nic oficjalnie. Pewnych
rzeczy musiałam się domyślać, na pytania nikt nie odpowiadał.

I tutaj muszę wrócić do Tadeusza, ponieważ losy życiowe się ciągle
przeplatają. Po wyzwoleniu otrzymał pracę we Wrześni w Urzędzie Bezpieczeństwa
jako zastępca komendanta. Jak na młody wiek to była bardzo wysoka
funkcja. Zaprowadzał porządek w całym powiecie. Jeździł wspaniałym motocyklem
w skórzanym ubraniu, z pełnym uzbrojeniem (karabin maszynowy, pistolet). Wpadł
kiedyś do nas motorem na podwórze z takim impetem, że aż kury fruwały. Mama
wiedziała, że przyjechał ją zabić, schowała się gdzieś w tajemnicze
miejsce. Naraz uwagę jego odciągnął nadlatujący niemiecki dwupłatowiec,
wyciągnął karabin maszynowy i zaczął do niego strzelać. Dziadek zaczął
wrzeszczeć, żeby przestał, bał się ostrzału niemieckiego. Samolot odleciał,
Tadeusz zapuścił motor i odjechał. Był zawsze pewny swego, bardzo zarozumiały,
jednocześnie siejący lęk. Miał pełnię władzy i wykorzystywał ją. Robił
porządki w całym powiecie. Jednak nie dane mu było się cieszyć zbyt długo
zajmowanym stanowiskiem, a wszystko przez miłość.

Zakochał się w ładnej blondyneczce, Halince Wesołowskiej, której brat był
w Armii Krajowej. Działo się to wszystko na przełomie 1945/46. Partyzantka AK
jeszcze walczyła w podziemiu z nową władzą. Brat Halinki był
poszukiwany. Przeprowadzano rewizje i podczas jednej z nich Tadeusz przebywał
u Wesołowskich. Wylegitymowano go i dla niego rozpoczęło się piekło. Posądzono
go o współpracę z AK i aresztowano. Osadzono go we Wronkach. Było to i jest
najcięższe więzienie w Polsce. Zbudowali je Prusacy pod koniec XIX w. Wielki,
ponury budynek straszy w tym miasteczku kilkadziesiąt lat. Grube mury,
maleńkie okienka i żadnej możliwości ucieczki. Nazywają je polskim
Alkatraz. Tadeusza dowożono z Wronek na przesłuchania do Wrześni. Zarzucono mu
szpiegostwo na rzecz AK i zdradę ojczyzny. Czekał za to najwyższy wymiar kary
--- kara śmierci. Nie było z nim żadnego kontaktu, nikt go nie mógł
odwiedzać. Siedział w izolatce, a przesłuchania były straszne, chcieli z niego
wyciągnąć z kim współpracował, jakie miał powiązania z AK. Po prostu miał się
przyznać do tego, czego nigdy nie robił i o czym nie miał pojęcia. Do Wrześni
wożono go pociągiem i podczas jednego powrotu do Wronek chciał wyskoczyć. Nie
mógł pewnie już dłużej wytrzymać i wtedy zaostrzyli rygor. Był chyba bardzo
niepokornym więźniem i te ucieczki były bardzo do niego podobne. Jaka jest
prawda o nim i jaki otrzymał wyrok, tego nikt nie wie. Rodzina otrzymała
wiadomość, że Tadeusz zabił się podczas próby ucieczki i został pochowany we
Wronkach.

Wiadomość taką otrzymali dwa tygodnie po rzekomym pogrzebie. Kiedy
pojechali na cmentarz, pracownicy nie umieli im wskazać prawidłowego
grobu. Babcia strasznie przeżyła to wydarzenie, cała rodzina opłakiwała go,
dano na mszę niejeden raz i cierń pozostał. Czas nie całkowicie wyleczył rany,
a wręcz je rozszarpał po odwilży w 1956r. Mieszkaniec Gutowa Wielkiego,
słuchacz Radia Wolna Europa, przywiózł Rutkowskim wiadomość, którą usłyszał po
północy. Wśród trzasków i zagłuszań dotarła do niego wieść, że Tadeusz
Rutkowski przesyła rodzinie pozdrowienia z dalekiej Syberii. Pozdrowienia
przekazał do Radia WE pewien Niemiec, który został zwolniony z rosyjskiej
niewoli. Niepokój wkradł się w serca całej rodziny, a babcia zaczęła poważnie
chorować. Nie była to jednak ostatnia wiadomość. Rok później wrócił jakiś
mężczyzna spod Gniezna, też z Syberii. Po trzech dniach zmarł. Zdążył
przekazać swej rodzinie kilka wiadomości o Tadeuszu. Pracował on rzekomo na
Syberii w kołchozie jako traktorzysta, założył rodzinę. Są to wszystko
cząstkowe wiadomości. Wiem, że Florian zaczął intensywnie go poszukiwać przez
Czerwony Krzyż, ale nigdzie na żadnych listach nie figurował. Poszukiwania
przerwała śmierć babci w 1958r., zmarła na serce. Pochowana została na
cmentarzu przy ul. Gnieźnieńskiej.

* Szkoła podstawowa Gutowo Małe

Na początku lutego 1945r. organizowano placówki oświatowe w powiecie. Odbyły
się zapisy wszystkich dzieci, które podlegały obowiązkowi szkolnemu. W czasie
okupacji nie działały żadne szkoły, więc tych roczników było bardzo
dużo. Szkoła znajdowała się przy drodze do Ostrowa. Był to budynek z czerwonej
cegły, z jedną dużą salą lekcyjną i mieszkaniem dla nauczyciela. W tej sali
uczyły się wszystkie zaległe roczniki razem. W czerwcu dokonano podziału
według wyników w nauce i utworzono klasy. Tym trudnym procesem tworzenia
szkoły w Gutowie zajmował się uczący już tutaj przed wojną
p. Bączkowski. Okres wojny spędził w obozie koncentracyjnym, wygląd jego
budził litość. Był bardzo wychudzony, słaby, kaszlący; po prostu chory. Wrócił
jednak na placówkę, którą opuścił, aby kontynuować dzieło życia. To jest cecha
prawdziwego nauczyciela. Ubierał się w mundur wojskowy. Spotkałam się z nim
1 września 1945r. Lekcje odbywały się na trzy zmiany. Chodziliśmy do szkoły
bez książek i zeszytów. Każdy uczeń miał małą tabliczkę i rysik. Nauczyciel
pisał na tablicy, a my na naszych tabliczkach. Musieliśmy też mieć ściereczkę
do mazania. Trudno było uruchomić produkcję papieru i podręczników, gdyż
Niemcy niszczyli fabryki, a to co zostało ukradli Rosjanie. Kraj nasz był tak
zniszczony i zubożały, że trudno sobie to dzisiaj wyobrazić. Brakowało poza
tym kadr, a właściwie to nie było nic. Wszystko należało zaczynać od
początku. Duży nacisk położono na rozwój oświaty. Wieczorami do szkoły
uczęszczali dorośli na kursy dla analfabetów, ponieważ ci co ukończyli szkołę
przed wojną nie zawsze umieli się podpisać.

Największą radością dla nas było przekazanie pałacu na potrzeby
szkoły. Znajdował się w pięknym jeszcze wówczas parku, nie był
zniszczony. Pamiętam z jaką radością przenosiłam ławki ze starej szkoły do
pałacowych klas. Przed wniesieniem myliśmy je przy stawku w parku. Po lekcjach
często biegłam do parku, aby pospacerować w tym zakazanym dotąd
miejscu. Odkrywałam tajemnicze tutaj miejsca. Stały piękne bramy. Mur
okalający park był z pięknej czerwonej cegły, dróżki i ścieżki
zadbane. W głębi stała figurka przedstawiająca jakąś boginkę. Sam pałac był
również bardzo piękny. Jest to budynek piętrowy z końca XIXw. Przed pałacem
w zadbanym klombie rosły różnokolorowe kwiaty. Do pałacu prowadziły szerokie
schody, po bokach kolumny. Sale były na tyle duże, że mogliśmy z powodzeniem
urządzać klasy.

Stopniowo otrzymywaliśmy podręczniki i czasopisma. Pierwszą moją książką był
"Elementarz" Mariana Falskiego, wspaniały podręcznik, z którego później sama
uczyłam dzieci. Pierwsza książka! Po przeprowadzce do pałacu zatrudniono
więcej nauczycieli, moją wychowawczynią została pani Olga Celińska, starsza,
samotna osoba, która była wspaniałą nauczycielką. Jak bardzo chciałam się
uczyć! Muszę przyznać, że szło mi to wcale nieźle. Koleżanką moją była od
początku Ela Kosmala, siedziałam z nią w jednej ławce, po lekcjach też
spędzałyśmy dużo czasu razem.

Zimą szaleństwo odbywało się na stawku w parku. Stawek miał strome, dość
wysokie zbocza i po nich zjeżdżaliśmy na lód. Formowaliśmy kolejkę i trzymając
się za barki mknęliśmy w dół. Ile było przewrotów i śmiechu!Moje dybki bardzo
mi się wtedy przydawały. Zaczęto również organizować nam czas
pozalekcyjny. Uczennice z Liceum zorganizowały drużynę harcerską. Ja należałam
do zuchów, jaka byłam zachwycona działalnością tych młodych dziewczyn, tak
bardzo mi się to wszystko podobało. Mieliśmy zbiórki raz w tygodniu, to były
prawdziwe, niewymuszone spotkania. Uczyliśmy się piosenek, gier, zabaw
i często maszerowaliśmy czwórkami przez wieś śpiewając ulubione
piosenki. Urządzaliśmy również pikniki w najbliższym lasku
zw. borkiem. Zabieraliśmy jedzenie i szliśmy tam właśnie się pobawić
np. w podchody.

Z tego okresu pamiętam najwięcej zabaw w terenie. Nie mieliśmy żadnego sprzętu
sportowego, a zabawa była przednia. z okazji Dnia Dziecka cała szkoła bawiła
się w borku. To były dla mnie niezapomniane chwile. Bardzo lubiłam szkołę,
nauczycieli i swoją klasę. Myślę, że ze wzajemnością. Recytowałam bardzo
trudne utwory na akademiach szkolnych, byłam chwalona i nagradzana. Jedynie
szkoła przynosiła mi tyle radości, tutaj czułam się spokojna i bezpieczna.
Mieszkałam z mamą w bocznym mieszkaniu. Miałyśmy pokój i kuchnię. Nic poza
tym. Żadnych środków do życia.

* Tata nie wraca ranki i wieczory...

Byłyśmy na garnuszku u dziadka Jadłowskiego. Garnuszek był zazwyczaj
pusty. Mama pomagała w gospodarstwie, najczęściej w polu, chociaż muszę
obiektywnie stwierdzić, że do pracy nie paliła się. Wysyłała mnie na śniadanie
do babci. Siadałam na ławce przy piecu i czekałam. Obrazek: babcia smaży
dziadkowi jajka. Cisza. Przekłada jajka na talerz. Kładzie mu na
stół. Wyczyszczoną patelnię podaje mi, abym do reszty wyskrobała. Dziadek
wstaje, sprawdza, ile mi zostało i zawsze w ten sam sposób komentuje: "Nie
byde na znojdora robił". Kiedykolwiek wykładam jajka z patelni, ten obraz
wraca jak mantra.

W letnich miesiącach 1945r. przeszła straszna burza. Takie zjawiska zdarzają
się często, ale takiej ściany deszczu, nawałnicy i uderzeń piorunów nie
przeżyłam wiele razy. Uderzało raz za razem, aż w końcu walnęło
w zabudowania. Czuć było siarką. Siedziałam znowu na moim miejscu przy
piecu. Cała rodzina skupiona była w kuchni, chyba dziewięć osób. Powstał
straszny krzyk. Pojawiało się coraz więcej dymu. Mimo padającego deszczu
biegali do studni i z wiadrami wody na strych, ponieważ tam paliły się
makowiny. Pobiegłam z mamą do naszego mieszkania i tam okazało się, że piorun
nas też odwiedził, porysował ściany i pod obrazem przebił się do babcinego
pokoju, a stamtąd do kuchni i wpadł w ziemię przy piecu.

Na środku podwórka stała studnia z kołowrotem. Wody nie było za wiele, ale
starczało dla rodziny i zwierząt. Dlaczego wspominam o studni? W okresie
zamieszania wojennego Jadłowscy nazbierali różnego rodzaju broń. Po wojnie
były komunikaty, aby zdać broń. Oni jednak nie zdali, tylko wrzucili ją do
studni. Co za głupota? Po jakimś czasie woda nie była zdatna do picia.

Pole dziadka usytuowane było ok. 200 m. od domu. Miało kształt trójkąta
i znajdowało się pomiędzy drogą polną, kanałem a torami kolejowymi. Hodowali
krowy, nie mieli łąki, więc trzeba je było wypasać na rowach. Jedyny rów był
przy torach kolejowych. Obowiązkiem moim było wypędzać kilka krów z cielętami
z obory, drogą, przez tory i odpowiednio je zagnać na rów przy torach. Miałam
wtedy siedem lat i szłam tylko z kijem jako pomocnikiem. Pociągi osobowe
i towarowe pędziły w obu kierunkach, a ja się tak bałam, żeby krowy nie weszły
na tory. Nieraz ktoś mi pokiwał z okien pociągu. Teraz z jedną krową nie
poradziłabym sobie, ale to jeszcze nie koniec. Krowy zajmą dużą część mojego
życia, mojego wolnego czasu, a tak zawsze się ich bałam.

Moja wychowawczyni, pani Olga Celińska, hodowała kilka kurek. Podczas przerwy
podeszła do mnie i poprosiła, abym jej przyniosła od dziadka trochę
zboża. Dała mi torebkę mogącą pomieścić chyba z dwa kilogramy. Ucieszyłam się,
że to ja właśnie będę mogła jej pomóc i ruszyłam w podskokach do
domu. Wiedziałam, że dziadek ma tony zboża na strychu, że żadnego problemu nie
powinno być. Najpierw poszłam do mamy, a ona wysłała mnie do babci. Weszłam do
kuchni, babcia krzątała się przy piecu, a dziadek czytał przy oknie
gazetę. Przedstawiłam moją prośbę i nagle słyszę wrzask: Wynocha! Nie chciało
mi się wracać do szkoły, ale musiałam się przełamać.

Sytuacja materialna mamy i moja przedstawiała się nader
niekorzystnie. W czasie okupacji pracowała u Niemców, po zakończeniu wojny
znalazła się bez środków do życia. Nadrenia, gdzie przebywał mój ojciec
w niewoli, została wyzwolona na początku 1945r., w maju podpisano traktat
pokojowy. Wszyscy Polacy, którzy przeżyli, wracali do domów. Bracia mamy,
Marian i Czesław, którzy również przebywali w niewoli na terenie Niemiec,
wrócili. O moim ojcu nikt nic nie wiedział. Mijały dni, tygodnie i miesiące
bez żadnych wiadomości. Zawieszenie w próżni. Mama płakała, dziadek nas
wypędzał, babcia pokryjomu przynosiła jedzenie. We wrześniu 1945r. poszłam do
szkoły w biednych, poprzerabianych ciuchach. Na ojca tak naprawdę to nie
czekałam, nie znałam go. Atmosfera jednak stawała się nie do zniesienia.

W grudniu wrócił! Pamiętam, jak wchodzi do domu facet w wojskowym szynelu,
najpierw cisza, potem wszyscy krzyczą do mnie, że tata
przyjechał. Przyglądałam się temu powrotowi z wielką obojętnością. Zresztą
przez całe życie nie odczuwałam do niego żadnych więzi emocjonalnych. Zaczęło
się wielkie picie. Pędzili bimber. Nie było jednego człowieka
trzeźwego. Babcia nie mogła zdążyć z przygotowywaniem jedzenia. Mięso z małych
koźląt piekła w chlebowym piecu. A ja, mimo zimowych chłodów, siedziałam pod
gruszą w rogu ogródka, zatykałam uszy, a i tak słyszałam wrzaski
i śpiewy. A gdzie był "mój tatuńcio" dotychczas? Po odzyskaniu ziem północnych
i zachodnich bardzo wielu Polaków z rodzin wielodzietnych osiedlało się
właśnie na tych terenach. Dwaj bracia mojej mamy, Marian i Czesław, znaleźli
domy poniemieckie we Wrocławiu, założyli rodziny i tam zamieszkali. Młodszy
brat ojca, Stefan, osiadł w Sławnie przy ul. Zeromskiego 10, założył
restaurację. Domyślam się, że to był budynek przystosowany do tych celów. Do
niego prosto z Niemiec pojechał mój ojciec i tam przebywał ponad pół
roku. Otrzymał stanowisko kierownika poczty w Sławnie, dom i wszystko układało
się jak najlepiej. Zatęsknił jednak za rodziną i przyjechał do Gutowa Małego,
aby nas zabrać do Sławna po Bożym Narodzeniu. Mama moja nie chciała rozstać
się ze swoją rodziną --- co za pech --- a poza tym bała się, że Niemcy wrócą
na te tereny. Awantury. Płacz. Zostało po staremu. Ojciec bez pracy i bez
zawodu, na utrzymaniu u dziadków jednych i drugich.

Przez cały okres okupacji nie uczęszczaliśmy do kościoła. Naszym kościołem
była Fara, tam byłam chrzczona. Jednak przez 6 lat nie chodziliśmy tam, bo nie
wolno było. Chcąc się dostać do Wrześni należało mieć przepustkę od Niemca,
który zarządzał Gutowem. W sumie we Wrześni byłam dwa razy; jeden raz u
dentysty, drugi raz u fotografa. Po wyzwoleniu obudziły się we wszystkich
uczucia religijne. W Gutowie stała figura Matki Boskiej i w maju 1945r. bardzo
dużo mieszkańców udawało się wczesnym wieczorem w to miejsce, aby uczestniczyć
w śpiewaniu pieśni maryjnych. Byłam wtedy bardzo pobożna i mile wspominam ten
okres. Natomiast w każdą niedzielę jechałam z babcią i dziadkiem na mszę do
Wrześni. Dziadek był najbogatszym gospodarzem we wsi, miał piękne konie i dwie
bryczki. Mijaliśmy ludzi tłumnie spieszących do kościoła i pamiętam dumę
dziadka, który jako jedyny miał powóz. Co prawda ukradziony Niemcom, ale mógł
szpanować. Dziadek wyjeżdżał teraz do Wrześni codziennie do knajpy Kulczaka,
wypił parę setek i wracał do domu na obiad. Gospodarstwem zajmował się przede
wszystkim Wiktor, pomagali mu pozostali a więc moja mama, Czesia i Basia --–
jej siostry, Zygmunt --– jej brat. Dziadek wydawał rano dyspozycje
i wyjeżdżał. Po powrocie sprawdzał wykonane prace i wyrażał swoje ciągłe
niezadowolenie. Pomagał również Bogdan po powrocie z wojska. Walczył z bandami
UPA w Bieszczadach, został odznaczony Virtuti Militari. Bogdan był bardzo
pracowity i dbał o porządek w obejściu. Babcia zajmowała się przyrządzaniem
posiłków, pozostali pracowali przy karmieniu trzody, krów i koni. Babcia
zajmowała się drobiem. Gospodarstwo było duże, każdy miał co robić a ja pasłam
krowy.

Nie chciałabym przytaczać samych czarnych scenariuszy życia w Gutowie
Małym, ale tak się jakoś układał, że nie mogę znaleźć nic
pozytywnego. Ukończyłam pierwszą klasę z wyróżnieniem i szkoła była dla mnie
miejscem, gdzie czułam się wspaniale. 26 września 1946r. urodził się mój brat
Tadeusz. Wtedy zaczęła się bieda na całego. Mama nie mogła już u dziadka
pracować, gdyż zajmowała się dzieckiem. Skończyła się jakakolwiek
pomoc. Chciałam dodać, że chrzestnymi Tadeusza byli Florian Rutkowski
i Czesława Jadłowska. Przyjęcie było więcej niż skromne.

* Nadarzyce

Ojciec zaczął się rozglądać za otrzymaniem jakiejś działki. Było to trochę
późno, ponieważ reforma rolna już się skończyła i w zasadzie ziemia została
rozdzielona. Dość długo czekał na decyzję Starostwa we Wrześni i na wiosnę
1947r. otrzymał działkę 10-hektarową w Nadarzycach.

Nadarzyce to bardzo stara osada, prawdopodobnie z trzynastego wieku. Jak sama
nazwa wskazuje wieś ta leży nad rzeką. Z jednej strony rzeki wznoszą się dość
wysokie wzgórza, potem rzeka, dużo łąk i wieś. We wzgórzach wykopano przełęcz
i to miejsce po obu stronach nazywano cegielnią. Prawdopodobnie przed wielu
laty wyrabiano tu cegły. Kawałki cegieł można było tam jeszcze
znaleźć. Solidny most na Wrześnicy świadczy, że przewożono tu ładunki. Zresztą
dużo gliniastej gleby ułatwiało produkcję. Wioska była typowo folwarczna,
składała się z pięciu czworaków, na końcu wioski stał budynek
dwurodzinny. Mieszkało w sumie 22 rodziny. Najważniejszym miejscem było
podwórze. Zajmowało dość duży teren. Od strony Wrześnicy stała stajnia, od
strony wsi duży spichlerz, przy drodze obora i obok kuźnia, a całość zamykał
dom właściciela. Był to dwurodzinny budynek, parterowy. Po drugiej stronie
drogi stały dwie olbrzymie stodoły. Teraz stoi tylko jedna, ale fundamenty
drugiej świadczą o solidnej budowie --– olbrzymie kamienie. Wydaje mi się, że
całość tej miejscowości świadczy o dobrej pruskiej robocie.

Mimo bliskości rzeki zawsze były problemy z wodą pitną. Dla
mieszkańców czworaków wybudowano cztery bardzo głębokie studnie, cembrowane,
z kołowrotem. Każdy mieszkaniec miał chlewik dla hodowli trzody, murowaną
ubikację i ogródek warzywny, kilka arów ziemi na uprawę ziemniaków oraz
piwnicę. Wszystkie mieszkania miały jednakowy rozkład. Wchodziło się przez
maleńką sień, w której znajdował się piec do pieczenia chleba i po
przystawianej drabinie wejście na strych. Kuchnia niewielka z maleńkim
okienkiem, szyby oprawione w żelazne ramy (zardzewiałe), zamiast podłogi
gliniana polepa, strasznie nierówna. Pokój dość przyjemny, podłoga drewniana,
jednak bez pieca. Tutaj okienko się otwierało. Wioska należała do parafii
w Gozdowie. W Nadarzycach był krzyż, który stoi do tej pory, odprawiano tutaj
nabożeństwa majowe, w których uczestniczyły wszystkie kobiety i dzieci. W 1945
roku przeprowadzono reformę rolną w wyniku której wszyscy mieszkańcy
czworaków mogli otrzymać działki 8--10 ha. Podzielono również budynki
gospodarcze i łąki. Wrześnica była zawsze kapryśna i na wiosnę zalewała dużą
część łąk, dlatego jeszcze w XIX wieku pobudowano tamy przy budynkach
gospodarczych. Zagospodarowanie wioski, budynków gospodarczych, wykorzystanie
łąk, dobra melioracja (głębokie kanały), drogi polne i zadrzewienie ich
poboczy (obsadzone drzewami lipowymi) świadczy o dobrym fachowcu, który kiedyś
te ziemie posiadał.

Jest rok 2010. Dewastacja kompletna. Czworaków już w zasadzie nie ma
,pobudowano kilka domów, każdy w innym stylu. Budynki gospodarcze wykorzystuje
się do upadłego. Totalna ruina.

Dokładnie 4 mają 1947r z samego rana pożyczonym wozem z całym dobytkiem
ruszyliśmy z Gutowa Małego do Nadarzyc. Dobytku nie było za wiele, trochę
mebli kuchennych (szafa, stół i dwa krzesła) i pokojowych (dwa łóżka, szafa,
stół i dwa krzesła), kilka garnków i to wszystko. Ojciec otrzymał konia
"Gniadego" od swoich rodziców i to był inwentarz żywy. Był piękny majowy
dzień. Siedziałam na koźle między rodzicami, miałam letni kapelusik na głowie
z kwiatkami, jak ja go nie cierpiałam. Moja mama wcisnęła mi go jako symbol
lepszego pochodzenia, zresztą całe życie miała kompleks niższości,
a największym wyróżnieniem dla niej to było, jak ktoś się do niej zwracał
"Pani Rutkowska", powtarzała ten zwrot zawsze z wielką estymą. Tymczasem
w czasie podróży trzymała na kolanach Tadeusza, który miał pół roku
i spokojnie spał. Ojciec powoził.

Dziadek Jadłowski nie dał obiecanej krowy, babcia nie dała obiecanych kur,
żaden z Jadłowskich nie pomagał nam się przeprowadzać, byliśmy zupełnie sami
i zdani na własny los. Po dojechaniu na miejsce, zaczęli się rozpakowywać,
znosić i ustawiać meble, ja w tym czasie i nie tylko zajmowałam się
Tadeuszem. Po południu poszłam z mamą nad Wrześnicę. Po raz pierwszy widziałam
rzekę. Byłam zachwycona. Czysta woda wartkim nurtem płynęła z kierunku Wrześni
do Gozdowa. Pływały w niej ryby --– płocie, które później będę łowiła
koszykiem, aby z nich przyrządzać smaczne jedzonko. Mama była bardzo smutna,
kiedy ja zachwycałam się pięknem krajobrazu, ona rozpaczliwie płakała. Nigdy
nie zaakceptowała Nadarzyc.

Najpierw kupiono kozę, aby mieć trochę mleka dla Tadeusza. W chlewiku pojawiły
się świnki, stopniowo kupowano krowy, były ich trzy, trochę kur, narzędzia
gospodarcze –-- to wszystko trwało, stale byli na dorobku. Ich pole znajdowało
się ok. 2 km od podwórza, w tzw. "wążku", pod Bierzglinem i Sołecznem. Było
naturalnie odizolowane od pozostałych, z jednej strony bardzo głęboki kanał,
z drugiej cierniste krzewy tarniny, a z niej smaczne, cierpkie owoce, które
można było jeść po pierwszych przymrozkach. Brałam bańkę i obdzierając się,
zbierałam do jedzenia. Na kanałach rosły również jeżyny i dzikie grusze
tzw. ulęgałki. Jedna wielka grusza, nazywana przez wszystkich "smolarą" rosła
za Wrześnicą w stronę Neryngowa. Na to drzewo rosochate nie można było wejść,
czekaliśmy kiedy opadną. Duże, smaczne gruszki. Przy domu mieliśmy ogródek
warzywny. Tutaj nauczyłam się kopać, sadzić rośliny i uprawiać je. Rodzice nie
mieli czasu, ponieważ praca w polu zajmowała im całe dnie. Nikomu nie przyszło
do głowy, żeby posadzić drzewka w ogródku. Wielką radość sprawiało mi
znalezienie jednej chociaż czereśni, która rosła przy domku dróżnika
w Gozdowie albo znalezienie spadłego jabłka przy jakimś gospodarstwie. Z tego
okresu pochodzi u mnie niesamowita ochota do sadzenia drzewek, zakładałam
sady, gdzie się tylko osiedliłam i nie zawsze doczekałam się owoców. Przez
całe życie porządkowałam teren, zakładałam ogródki, sadziłam truskawki, które
w dzieciństwie były dla mnie rarytasem.

* Szkoła w Gozdowie

W maju przeniosłam się z Gutowa do Gozdowa do drugiej klasy. Jakie tortury
przeżywałam, to sobie trudno wyobrazić. Tak bardzo lubiłam szkołę w Gutowie,
miałam koleżanki, dobrą opinię i wspaniałych nauczycieli. Tutaj wszystko
nowe. Przyglądano mi się z zaciekawieniem. Wychowawczyni posadziła mnie, o
zgrozo, z chłopcem, w ostatniej ławce. Jak ja się źle czułam. Nie tylko źle,
fatalnie. W Gutowie uczyliśmy się w wymarzonym pałacu, wokół park, a tutaj
szkoła na górce, pusto i tak nieswojo. Wszystko obce. Na koniec roku miałam
oceny bardzo dobre przeniesione na arkuszu ocen z Gutowa. W trzeciej klasie
sytuacja się diametralnie zmieniła. Kierownikiem szkoły był w dalszym ciągu
Pan Becelewski, bardzo schorowany człowiek, pewnie po obozie. Uczyła jeszcze
Pani Sliwińska-–Kaczorowska, Pani Blauman, Pani Anioła, natomiast wychowawcą
moim w trzeciej klasie był Pan Adamski. W gronie nauczycielskim wybuchały
konflikty, stale się kłócili na korytarzu. Nie mogłam wejść w rytm pracy
szkoły i trzecia klasa była dla mnie fatalna. Wychowania fizycznego uczył mnie
kierownik, lekcji wcale nie było, a oceny wystawiał przed okresem
z musztry. Trzeba było wykonać zwroty w lewo, w prawo i w tył. Przecież to
umiałam, tylko moje dyby nie pozwalały się prawidłowo ustawić. W czwartej
klasie znowu rotacja kadr. Kierownik szkoły zmarł, grób jego znajduje się na
cmentarzu w Gozdowie. Bardzo przeżyłam jego śmierć, często zachodziłam na
cmentarz. Kiedy byłam w czwartej klasie nie było już Adamskiego i Anioły,
przyprowadziło się małżeństwo nauczycieli z Litwy --- Państwo Charutowie:
Józef i Helena, cudowni nauczyciele i ludzie. Kierownikiem szkoły został Pan
Charuta, był również moim wychowawcą. Nareszcie odnalazłam swoje miejsce
w szkole, znowu zostałam najlepszą uczennicą. Pan Charuta nie mógł być dalej
kierownikiem, ponieważ nie chciał się zapisać do partii i w następnym roku
kierownikiem został Pan Józef Szafraniak z Zielińca.Odeszła Pani Blaumanowa.

Szkoła w Gozdowie jest podobna do szkoły w Gorazdowie. Posiadała dwie duże
sale lekcyjne, a trzecią izbę wygospodarowano z mieszkania
nauczycielskiego. Nauczanie odbywało się na dwie zmiany. Klasy były bardzo
liczne, przydzielono nam jedną salę w pałacu. Trzeba było chodzić pod górkę
i z górki. Pałac stał na wzniesieniu, piękny park dookoła. Najstarsza wzmianka
o osadzie pochodzi z 1136r. Dawniej pisano też Gwozdowo. Nazwa pochodzi
prawdopodobnie od nazwiska Gozd, Gwozd, Gozdek (gozd, gwozd --- las,wzgórze
leśne). W Gozdowie znajduje się neogotycki kościół z 1881--83. Na cmentarzu,
w grobowcu rodzinnym, pochowany jest jeden z dowódców powstania
wielkopolskiego --- gen. Kazimierz Grudzielski. W Gozdowie były dwie własności
ziemskie; większa należała do Sulerzyckich, mniejsza do Koteckich. Przy
kościele pochowano gen. Abrahama. Wg "Krótki opis Wrześni
i gospodarstw powiatu wrzesińskiego" z 1929r. "Gozdowo dobra rycerskie, dawny
majątek kanoników gnieźnieńskich, w czasie zaborczym przeszedł w prywatne ręce
niemieckie, pozostając w nich do 1922r., w którym to roku powraca znów do rąk
polskich. Właścicielem majętności Gozdowo jest p. inż. roln. Tadeusz
Wyganowski. Obszar dworski liczy 318 ha". Trochę chaotyczne te wiadomości, ale
tyle udało mi się zebrać z różnych źródeł.

Do szkoły, o której piszę, uczęszczały dzieci z Gozdowa, Gozdowa Młyna,
Sołeczna, Nadarzyc, a od piątej klasy z Zielińca i Janowa. Klasy były bardzo
liczne, a w dodatku wprowadzono klasy łączone. W jednej sali lekcyjnej uczyło
się do sześćdziesięciu uczniów. Siedzieliśmy po trzech w ławce. Jaka straszna
ciasnota. Niewiele się mogliśmy nauczyć. W dodatku Ministerstwo wymyśliło,
żeby po piątej, szóstej i siódmej klasie, zdawać egzaminy promocyjne. Komisja
złożona z nauczycieli, najpierw egzamin pisemny z języka polskiego
i matematyki, później ustny. Na ustnym wyciągało się kartki, były trzy
pytania. Nauczyciele prowadzili dodatkowe zajęcia, aby przerobić materiał. Był
to obłęd, praktycznie w szkole byliśmy cały dzień. Najgorszy egzamin był
w siódmej klasie, dochodził język rosyjski, którego uczyliśmy się od klasy
piątej, a komisja powiększała się o osoby z władz powiatowych czy
wojewódzkich. Na egzaminie z matematyki Pani Charutowa podsunęła mi
najtrudniejszą kartkę, wiedziała, że sobie poradzę. Moją koleżanką na początku
była Helena Ignaszak z Nadarzyc, a od piątej klasy Teresa Konieczna
z Zielińca. Za moje wyniki w nauce i zachowanie zostałam wysłana na zimowisko
do Poznania. Była to moja pierwsza podróż pociągiem. Jednak z tego okresu mam
złe wspomnienia, nie dorównywałam strojem i wyglądem do reszty i to takie
przykre. W szkole organizowałam stale jakieś przedstawienia na imprezy, próby
mieliśmy w parku na trawie. Nigdy nie widziałam żadnych tańców ludowych,
jednak moje krakowiaki i oberki wychodziły przednio. Sami sobie śpiewałyśmy,
tańczyły same dziewczynki. Byłam bardzo zaangażowana w życie szkoły, miałam
jakiś talent do przewodzenia. W siódmej klasie zaczęłam zastanawiać się nad
swoją przyszłością. Najpierw chciałam iść do liceum choreograficznego
w Poznaniu, ale pan Charuta odradził mi i za jego sugestią wybrałam liceum
pedagogiczne.

Droga do szkoły to prawdziwa droga przez mękę. Wyjście z domu na drogę główną
w porze deszczowej to błoto pod kolana. Szliśmy grupkami lub
pojedynczo. Zajmowało to ponad pół godziny. Wozy konne, bo nic więcej po tej
drodze nie jeździło, poruszały się zawsze w przeciwnym kierunku. W porze
wielosetletniej wypasał krowy przy drodze jakiś niepełnosprawny
człowiek. Chłopcy go przezywali i dokuczali mu, a on z wielkim kijem gonił
wszystkich, rzucał kamieniami. Działo się to w drodze powrotnej ze szkoły
i wtedy uciekaliśmy polami nad Wrześnicę, wydłużało to strasznie czas
powrotu. Jeden dzień w tygodniu chodziliśmy na religię do kościoła, po
lekcjach. Ksiądz strasznie się jąkał (pozostałość po obozie), ale ja byłam
bardzo religijna i wcale mi to nie przeszkadzało. Tu również przyjęłam
pierwszą komunię świętą, przyjęcia nie pamiętam, bo go chyba wcale nie było.

* Codzienność w Nadarzycach

Początki wszędzie są trudne. Przyprowadziliśmy się właściwie
z niczym. Mieliśmy konia i kozę. Stopniowo przybywało inwentarza żywego;
w efekcie mieliśmy trzy krowy i kilka świń w chlewiku. Krowy były we wspólnej
oborze, a koń w stajni. Praca w polu była bardzo ciężka, ponieważ większość
prac wykonywało się ręcznie, np. przerywka buraków, a potem jeszcze raz
tzw. okrążka, najpierw na kolanach, a potem na stojąco. Zbiór też odbywał się
ręcznie. Każdego buraka podważało się tzw. hebrem i układało się
w rządkach. Następnie sierpem obcinało się liście, wkładało do koszyka
i wynosiło na kupki. Potem te buraki ładowano gablami na wóz i ojciec z wążka,
przez Wrześnicę wiózł do Neryngowa i ładował do wagonika kolejki
wąskotorowej. Wagonik musiał być wcześniej zamówiony i odstawiony na
bocznicę. Należało również od kogoś pożyczyć konia, ponieważ jednym nie dałoby
rady. Droga jesienią zawsze błotnista, daleko, wóz niewielki,
a buraków dużo. Ile tych kursów należało wykonać? Trzeba się spieszyć, bo za
postój wagonika płaciło się. Buraków uprawialiśmy chyba z hektar, opłacało
się. Z cukrowni otrzymywali pieniądze i worek cukru. Do Gniezna, aby odebrać
worek cukru, rodzice jechali konnym wozem. Jak jestem przy okopowych, to może
ziemniaki.



# Local Variables:
# ispell-local-dictionary: "polish"
# End:
