#+TITLE: Przepisy
#+AUTHOR: Aniceta Kubisiak

* Listówka

Składniki:
- 2 szklanki młodych świeżo rozwiniętych listków czarnej porzeczki z pędami
  (bez ugniatania)
- 1 litr żytniówki
- 0 pół łyżeczki kwasku cytrynowego
- 1 szklanka cukru drobnego

Listki opłukać, osączyć,włożyć do słoja, zalać przednią żytniówką i odstawić w
chłodne miejsce na tydzień. Po tygodniu zlać nalew przez sito, przefiltrować
przez sączek bibułowy i przechowywać w zamkniętej butelce. Liście ponownie
zalać 2 szklankami żytniówki i pozostawić w chłodnym miejscu na dwa
tygodnie. Tak jak poprzednio zlać nalew, a liście zasypać jedną szklanką
cukru, wymieszać i zostawić w cieple na 4--5 dni, mieszając kilka razy
dziennie, aż cukier się rozpuści. Zlać syrop przez sito i przefiltrować przez
lejek z watą. Połączyć z poprzednimi nalewami, wsypać kwasek cytrynowy i
wymieszać. Nalewkę szczelnie zamknąć i odstawić w ciemne chłodne miejsce.


* Smorodinowka

Składniki:
- 2 litry czarnych porzeczek (bez szypułek I liści)
- 1 litr spirytusu
- 1 litr listkówki
- 3 goździki
- 1 cm kory cynamonowej
- 2 laski wanilii
- 2 szklanki cukru drobnego
- 3 łyżki miodu

  Porzeczki zmiksować, przełożyć do słoja, zalać spirytusem, włożyć goździki,
  cynamon i rozciętą wzdłuż na pół wanilię. Pozostawić w cieple na miesiąc,
  często mieszając. Po tym czasie wynieść w chłodne miejsce i zapomnieć na
  rok.

  Po roku nalewkę zlać przez sito i przefiltrować przez sączek bibułowy, a
  owoce zasypać cukrem, dodać miód i pozostawić w cieple na 50-6 dni, często
  mieszając. Gdy cukier się rozpuści, zlać syrop i przesączyć go przez lejek z
  watą. Połączyć z nalewem i listkówką.

Pozostawić na 3 miesiące w chłodzie.

Owoce pozostałe po zlaniu syropu zawierają jeszcze sporo alkoholu i są bardzo
smaczne. Można je wykorzystać do deserów, koktajli lub jako nadzienie do
rogalików lub bułeczek drożdżowych.


# Local Variables:
# ispell-local-dictionary: "polish"
# End:
